<?php

/**
 * @file
 * Contains oauthost.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function oauthost_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the oauthost module.
    case 'help.page.oauthost':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Authentication Provider OST') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_theme().
 */
function oauthost_theme() {
  return [
    'oauthost' => [
      'template' => 'oauthost',
      'render element' => 'children',
    ],
  ];
}
