<?php

/**
 * @file
 * Contains epalreadydata.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function epalreadydata_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the epalreadydata module.
    case 'help.page.epalreadydata':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Data Avaialble from MySchool System') . '</p>';
      return $output;

    default:
  }
}
